# minibatch related
batch-size: 32
maxlen-in: 512
maxlen-out: 150

# optimization related
#criterion: loss
#early-stop-criterion: "validation/main/loss"
sortagrad: 0
opt: noam
transformer-lr: 5.0
transformer-warmup-steps: 25000
epochs: 100
patience: 0
accum-grad: 2
grad-clip: 5.0

lsm-weight: 0.1

# network architecture
## general
custom-enc-positional-encoding-type: rel_pos
custom-enc-self-attn-type: rel_self_attn
custom-enc-pw-activation-type: swish
## encoder related
etype: custom
custom-enc-input-layer: conv2d
enc-block-arch:
        - type: conformer
          d_hidden: 256
          d_ff: 2048
          heads: 4
          macaron_style: True
          use_conv_mod: True
          conv_mod_kernel: 15
          dropout-rate: 0.1
enc-block-repeat: 12
## decoder related
dtype: custom
custom-dec-input-layer: embed
dec-block-arch:
        - type: transformer
          d_hidden: 256
          d_ff: 2048
          heads: 4
          dropout-rate: 0.1
dec-block-repeat: 6
## joint network related
joint-dim: 512

# transducer related
model-module: "espnet.nets.pytorch_backend.e2e_asr_transducer:E2E"
